name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Clone upstream
        run: git clone --depth 1 https://github.com/rakyll/hey
      - name: Build
        run: cd hey && go build -o $HOME/hey
      - name: Run 5 second load test
        run: $HOME/hey -c 1 -q 1 -z 5 https://firecracker.exit.o6s.io/
